### PR TITLE
#1 issue

### PR DESCRIPTION
**Pull request by shreypilot**
i have modified index.html and i have added favicon and title in it

### CODE REVIEW

**Comment by uday03meh** [comment]
Hi, Seems like you have mistakenly added football icon that to multiple copies

image

Please make commits in this PR or make a new PR with 1 basketball icon and don't change the README file.

image

**Comment by uday03meh** [comment]
Can you please share a screenshot of the site after changes?

**Comment by shreypilot** [comment]
> Can you please share a screenshot of the site after changes?
yeah sure it seem like that but i haven't  modified in css file i have modified in only html file or add favico 
Capture

**Comment by uday03meh** [comment]
I think it does not look good. Can I close this PR?

**Comment by shreypilot** [comment]
> I think it does not look good. Can I close this PR?
yes, you can

**Pull request closed without merging**
